/** Generated by itemis CREATE code generator. */


import org.junit.*;
import static org.junit.Assert.*;

/**
 * Unit TestCase for Lampada
 */
@SuppressWarnings("all")
public class LampadaTest {
	
	private Lampada statemachine;	
	
	
	@Before
	public void lampadaTest_setUp() {
		statemachine = new Lampada();
		
		
	}

	@After
	public void lampadaTest_tearDown() {
		statemachine = null;
		
	}
	
	@Test
	public void test() {
		statemachine.enter();
		assertTrue(statemachine.isStateActive(Lampada.State.MAIN_REGION_OFF));
		statemachine.raisePoweron();
		assertTrue(statemachine.isStateActive(Lampada.State.MAIN_REGION_STANDBY));
		statemachine.raisePushbutton();
		assertTrue(statemachine.isStateActive(Lampada.State.MAIN_REGION_ON));
		assertTrue(statemachine.getVal() == 100l);
		statemachine.exit();
	}
}
