name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Compile Java code
      run: |
        cd ews_TVS/Progetto_TVS_Java/src/junit
        javac Zoo.java
    - name: Run tests
      run: |
        cd ews_TVS/Progetto_TVS_Java/src/junit
        java Zoo.java
