/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 09 17:20:14 CET 2022
 */

package counter_esempio;

import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class Counter_ESTest extends Counter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Counter counter0 = new Counter();
      counter0.inc();
      counter0.inc();
      counter0.inc();
      int int0 = counter0.inc();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Counter counter0 = new Counter();
      int int0 = counter0.dec();
      assertEquals(0, int0);
  }
}
